# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarimlar/anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1201, 800)
        MainWindow.setStyleSheet(".QWidget {\n"
"   background-color: beige;\n"
"}\n"
"\n"
"/* Nice Windows-XP-style password character. */\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    lineedit-password-character: 9679;\n"
"}\n"
"\n"
"/* We provide a min-width and min-height for push buttons\n"
"   so that they look elegant regardless of the width of the text. */\n"
"QPushButton {\n"
"    background-color: palegoldenrod;\n"
"    border-width: 2px;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 5;\n"
"    padding: 3px;\n"
"    min-width: 9ex;\n"
"    min-height: 2.5ex;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: khaki;\n"
"}\n"
"\n"
"/* Increase the padding, so the text is shifted when the button is\n"
"   pressed. */\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: #d0d67c;\n"
"}\n"
"\n"
"QLabel, QAbstractButton {\n"
"    font: bold;\n"
"}\n"
"\n"
"/* Mark mandatory fields with a brownish color. */\n"
".mandatory {\n"
"    color: brown;\n"
"}\n"
"\n"
"/* Bold text on status bar looks awful. */\n"
"QStatusBar QLabel {\n"
"   font: normal;\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"    border-width: 1;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 2;\n"
"}\n"
"\n"
"QComboBox, QLineEdit, QSpinBox, QTextEdit, QListView {\n"
"    background-color: cornsilk;\n"
"    selection-color: #0a214c; \n"
"    selection-background-color: #C19A6B;\n"
"}\n"
"\n"
"QListView {\n"
"    show-decoration-selected: 1;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color: wheat;\n"
"}\n"
"\n"
"/* We reserve 1 pixel space in padding. When we get the focus,\n"
"   we kill the padding and enlarge the border. This makes the items\n"
"   glow. */\n"
"QLineEdit, QFrame {\n"
"    border-width: 2px;\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border-color: darkkhaki;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* As mentioned above, eliminate the padding and increase the border. */\n"
"QLineEdit:focus, QFrame:focus {\n"
"    border-width: 3px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* A QLabel is a QFrame ... */\n"
"QLabel {\n"
"    border: none;\n"
"    padding: 0;\n"
"    background: none;\n"
"}\n"
"\n"
"/* A QToolTip is a QLabel ... */\n"
"QToolTip {\n"
"    border: 2px solid darkkhaki;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"/* Nice to have the background color change when hovered. */\n"
"QRadioButton:hover, QCheckBox:hover {\n"
"    background-color: wheat;\n"
"}\n"
"\n"
"/* Force the dialog\'s buttons to follow the Windows guidelines. */\n"
"QDialogButtonBox {\n"
"    button-layout: 0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 1061, 341))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(830, 40, 80, 170))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_Kayitekle = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Kayitekle.setObjectName("pushButton_Kayitekle")
        self.verticalLayout_2.addWidget(self.pushButton_Kayitekle)
        self.pushButton_Kayitsil = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Kayitsil.setObjectName("pushButton_Kayitsil")
        self.verticalLayout_2.addWidget(self.pushButton_Kayitsil)
        self.pushButton_Kayitara = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Kayitara.setObjectName("pushButton_Kayitara")
        self.verticalLayout_2.addWidget(self.pushButton_Kayitara)
        self.pushButton_Guncelle = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Guncelle.setObjectName("pushButton_Guncelle")
        self.verticalLayout_2.addWidget(self.pushButton_Guncelle)
        self.pushButton_Kayitlistele = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Kayitlistele.setObjectName("pushButton_Kayitlistele")
        self.verticalLayout_2.addWidget(self.pushButton_Kayitlistele)
        self.pushButton_Cikis = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Cikis.setObjectName("pushButton_Cikis")
        self.verticalLayout_2.addWidget(self.pushButton_Cikis)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 20, 277, 198))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_TCK = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_TCK.setMaxLength(11)
        self.lineEdit_TCK.setObjectName("lineEdit_TCK")
        self.horizontalLayout.addWidget(self.lineEdit_TCK)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_Sporcuadi = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_Sporcuadi.setObjectName("lineEdit_Sporcuadi")
        self.horizontalLayout_2.addWidget(self.lineEdit_Sporcuadi)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lineEdit_Sporcusoyadi = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_Sporcusoyadi.setObjectName("lineEdit_Sporcusoyadi")
        self.horizontalLayout_3.addWidget(self.lineEdit_Sporcusoyadi)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.comboBox_Sporkulubu = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_Sporkulubu.setObjectName("comboBox_Sporkulubu")
        self.comboBox_Sporkulubu.addItem("")
        self.comboBox_Sporkulubu.addItem("")
        self.comboBox_Sporkulubu.addItem("")
        self.comboBox_Sporkulubu.addItem("")
        self.comboBox_Sporkulubu.addItem("")
        self.comboBox_Sporkulubu.addItem("")
        self.comboBox_Sporkulubu.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_Sporkulubu)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.spinBox_Sporcukilosu = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_Sporcukilosu.setMinimum(50)
        self.spinBox_Sporcukilosu.setMaximum(140)
        self.spinBox_Sporcukilosu.setObjectName("spinBox_Sporcukilosu")
        self.horizontalLayout_5.addWidget(self.spinBox_Sporcukilosu)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.comboBox_Sporcucinsiyeti = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_Sporcucinsiyeti.setObjectName("comboBox_Sporcucinsiyeti")
        self.comboBox_Sporcucinsiyeti.addItem("")
        self.comboBox_Sporcucinsiyeti.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_Sporcucinsiyeti)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.checkBox_Evli = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_Evli.setObjectName("checkBox_Evli")
        self.horizontalLayout_7.addWidget(self.checkBox_Evli)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.checkBox_Bekar = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_Bekar.setObjectName("checkBox_Bekar")
        self.horizontalLayout_7.addWidget(self.checkBox_Bekar)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.calendarWidget_Dogumtarihi = QtWidgets.QCalendarWidget(self.groupBox)
        self.calendarWidget_Dogumtarihi.setGeometry(QtCore.QRect(420, 50, 321, 191))
        self.calendarWidget_Dogumtarihi.setObjectName("calendarWidget_Dogumtarihi")
        self.listWidget_Brans = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_Brans.setGeometry(QtCore.QRect(70, 240, 281, 91))
        self.listWidget_Brans.setObjectName("listWidget_Brans")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Brans.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Brans.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Brans.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Brans.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Brans.addItem(item)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(420, 20, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(70, 220, 91, 16))
        self.label_8.setObjectName("label_8")
        self.tableWidget_Sporcubilgiler = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_Sporcubilgiler.setGeometry(QtCore.QRect(10, 380, 1061, 281))
        self.tableWidget_Sporcubilgiler.setRowCount(100)
        self.tableWidget_Sporcubilgiler.setColumnCount(10)
        self.tableWidget_Sporcubilgiler.setObjectName("tableWidget_Sporcubilgiler")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 680, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_Kayitsayisi = QtWidgets.QLabel(self.centralwidget)
        self.label_Kayitsayisi.setGeometry(QtCore.QRect(130, 680, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Kayitsayisi.setFont(font)
        self.label_Kayitsayisi.setText("")
        self.label_Kayitsayisi.setObjectName("label_Kayitsayisi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1201, 21))
        self.menubar.setObjectName("menubar")
        self.menuYard_m = QtWidgets.QMenu(self.menubar)
        self.menuYard_m.setObjectName("menuYard_m")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuhakkinda = QtWidgets.QAction(MainWindow)
        self.menuhakkinda.setObjectName("menuhakkinda")
        self.menuYard_m.addAction(self.menuhakkinda)
        self.menubar.addAction(self.menuYard_m.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_Sporkulubu.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Sporcu Bilgileri"))
        self.pushButton_Kayitekle.setText(_translate("MainWindow", "KAYIT EKLE"))
        self.pushButton_Kayitsil.setText(_translate("MainWindow", "KAYIT SİL"))
        self.pushButton_Kayitara.setText(_translate("MainWindow", "KAYIT ARA"))
        self.pushButton_Guncelle.setText(_translate("MainWindow", "GÜNCELLE"))
        self.pushButton_Kayitlistele.setText(_translate("MainWindow", "LİSTELE"))
        self.pushButton_Cikis.setText(_translate("MainWindow", "ÇIKIŞ"))
        self.label.setText(_translate("MainWindow", "TC Kimlik Numarası"))
        self.label_2.setText(_translate("MainWindow", "Sporcu Adı:"))
        self.label_3.setText(_translate("MainWindow", "Sporcu Soyadı:"))
        self.label_4.setText(_translate("MainWindow", "Sporcu Kulübü:"))
        self.comboBox_Sporkulubu.setItemText(0, _translate("MainWindow", "Fenerbahçe"))
        self.comboBox_Sporkulubu.setItemText(1, _translate("MainWindow", "Galatasaray"))
        self.comboBox_Sporkulubu.setItemText(2, _translate("MainWindow", "Beşiktaş"))
        self.comboBox_Sporkulubu.setItemText(3, _translate("MainWindow", "Başakşehir"))
        self.comboBox_Sporkulubu.setItemText(4, _translate("MainWindow", "Trabzonspor"))
        self.comboBox_Sporkulubu.setItemText(5, _translate("MainWindow", "Göztepe Spor"))
        self.comboBox_Sporkulubu.setItemText(6, _translate("MainWindow", "Tekirdağ Spor"))
        self.label_5.setText(_translate("MainWindow", "Sporcu Kilosu:"))
        self.label_6.setText(_translate("MainWindow", "Sporcu Cinsiyeti:"))
        self.comboBox_Sporcucinsiyeti.setItemText(0, _translate("MainWindow", "Erkek"))
        self.comboBox_Sporcucinsiyeti.setItemText(1, _translate("MainWindow", "Kadın"))
        self.label_7.setText(_translate("MainWindow", "Medeni Hali:"))
        self.checkBox_Evli.setText(_translate("MainWindow", "Evli"))
        self.checkBox_Bekar.setText(_translate("MainWindow", "Bekar"))
        __sortingEnabled = self.listWidget_Brans.isSortingEnabled()
        self.listWidget_Brans.setSortingEnabled(False)
        item = self.listWidget_Brans.item(0)
        item.setText(_translate("MainWindow", "Güreş"))
        item = self.listWidget_Brans.item(1)
        item.setText(_translate("MainWindow", "Boks"))
        item = self.listWidget_Brans.item(2)
        item.setText(_translate("MainWindow", "Karete"))
        item = self.listWidget_Brans.item(3)
        item.setText(_translate("MainWindow", "Tekvando"))
        item = self.listWidget_Brans.item(4)
        item.setText(_translate("MainWindow", "Aikido"))
        self.listWidget_Brans.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("MainWindow", "Doğum Tarihi:"))
        self.label_8.setText(_translate("MainWindow", "Branş:"))
        self.label_10.setText(_translate("MainWindow", "Kayıt Sayısı:"))
        self.menuYard_m.setTitle(_translate("MainWindow", "Yardım"))
        self.menuhakkinda.setText(_translate("MainWindow", "Hakkında"))
