# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doktorbilgi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_doktor(object):
    def setupUi(self, widget_doktor):
        widget_doktor.setObjectName("widget_doktor")
        widget_doktor.resize(542, 490)
        self.label = QtWidgets.QLabel(widget_doktor)
        self.label.setGeometry(QtCore.QRect(80, 50, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(widget_doktor)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(widget_doktor)
        self.label_3.setGeometry(QtCore.QRect(80, 180, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_doktorgonder = QtWidgets.QPushButton(widget_doktor)
        self.pushButton_doktorgonder.setGeometry(QtCore.QRect(100, 390, 261, 41))
        self.pushButton_doktorgonder.setObjectName("pushButton_doktorgonder")
        self.textEdit_doktormesaj = QtWidgets.QTextEdit(widget_doktor)
        self.textEdit_doktormesaj.setGeometry(QtCore.QRect(80, 230, 341, 151))
        self.textEdit_doktormesaj.setObjectName("textEdit_doktormesaj")

        self.retranslateUi(widget_doktor)
        QtCore.QMetaObject.connectSlotsByName(widget_doktor)

    def retranslateUi(self, widget_doktor):
        _translate = QtCore.QCoreApplication.translate
        widget_doktor.setWindowTitle(_translate("widget_doktor", "Doktor Ekranı"))
        self.label.setText(_translate("widget_doktor", "Randevulu Hastadan Mesaj"))
        self.label_2.setText(_translate("widget_doktor", "Duyuru:Şuan da Hastadan bir bilgi bulunmamaktadır."))
        self.label_3.setText(_translate("widget_doktor", "Doktor Mesaj Ekranı"))
        self.pushButton_doktorgonder.setText(_translate("widget_doktor", "Hasta Ekranına Mesaj Gönder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_doktor = QtWidgets.QWidget()
    ui = Ui_widget_doktor()
    ui.setupUi(widget_doktor)
    widget_doktor.show()
    sys.exit(app.exec_())
