# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hastabilgi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_hastaekrani(object):
    def setupUi(self, widget_hastaekrani):
        widget_hastaekrani.setObjectName("widget_hastaekrani")
        widget_hastaekrani.resize(582, 487)
        self.label = QtWidgets.QLabel(widget_hastaekrani)
        self.label.setGeometry(QtCore.QRect(50, 70, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(widget_hastaekrani)
        self.label_2.setGeometry(QtCore.QRect(50, 140, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_hastagonder = QtWidgets.QPushButton(widget_hastaekrani)
        self.pushButton_hastagonder.setGeometry(QtCore.QRect(80, 380, 261, 41))
        self.pushButton_hastagonder.setObjectName("pushButton_hastagonder")
        self.textEdit_hastamesaj = QtWidgets.QTextEdit(widget_hastaekrani)
        self.textEdit_hastamesaj.setGeometry(QtCore.QRect(70, 190, 341, 151))
        self.textEdit_hastamesaj.setObjectName("textEdit_hastamesaj")

        self.retranslateUi(widget_hastaekrani)
        QtCore.QMetaObject.connectSlotsByName(widget_hastaekrani)

    def retranslateUi(self, widget_hastaekrani):
        _translate = QtCore.QCoreApplication.translate
        widget_hastaekrani.setWindowTitle(_translate("widget_hastaekrani", "Hasta Ekranı"))
        self.label.setText(_translate("widget_hastaekrani", "Randevulu Hasta Bilgi Mesajı"))
        self.label_2.setText(_translate("widget_hastaekrani", "Duyuru:Şuan da Doktordan bir bilgi bulunmamaktadır."))
        self.pushButton_hastagonder.setText(_translate("widget_hastaekrani", "Hasta Mesaj Gönder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_hastaekrani = QtWidgets.QWidget()
    ui = Ui_widget_hastaekrani()
    ui.setupUi(widget_hastaekrani)
    widget_hastaekrani.show()
    sys.exit(app.exec_())
