# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarimlar/ogrenci.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1236, 917)
        MainWindow.setStyleSheet(".QWidget {\n"
"   background-color: beige;\n"
"}\n"
"\n"
"/* Nice Windows-XP-style password character. */\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    lineedit-password-character: 9679;\n"
"}\n"
"\n"
"/* We provide a min-width and min-height for push buttons\n"
"   so that they look elegant regardless of the width of the text. */\n"
"QPushButton {\n"
"    background-color: palegoldenrod;\n"
"    border-width: 2px;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 5;\n"
"    padding: 3px;\n"
"    min-width: 9ex;\n"
"    min-height: 2.5ex;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: khaki;\n"
"}\n"
"\n"
"/* Increase the padding, so the text is shifted when the button is\n"
"   pressed. */\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: #d0d67c;\n"
"}\n"
"\n"
"QLabel, QAbstractButton {\n"
"    font: bold;\n"
"}\n"
"\n"
"/* Mark mandatory fields with a brownish color. */\n"
".mandatory {\n"
"    color: brown;\n"
"}\n"
"\n"
"/* Bold text on status bar looks awful. */\n"
"QStatusBar QLabel {\n"
"   font: normal;\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"    border-width: 1;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 2;\n"
"}\n"
"\n"
"QComboBox, QLineEdit, QSpinBox, QTextEdit, QListView {\n"
"    background-color: cornsilk;\n"
"    selection-color: #0a214c; \n"
"    selection-background-color: #C19A6B;\n"
"}\n"
"\n"
"QListView {\n"
"    show-decoration-selected: 1;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color: wheat;\n"
"}\n"
"\n"
"/* We reserve 1 pixel space in padding. When we get the focus,\n"
"   we kill the padding and enlarge the border. This makes the items\n"
"   glow. */\n"
"QLineEdit, QFrame {\n"
"    border-width: 2px;\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border-color: darkkhaki;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* As mentioned above, eliminate the padding and increase the border. */\n"
"QLineEdit:focus, QFrame:focus {\n"
"    border-width: 3px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* A QLabel is a QFrame ... */\n"
"QLabel {\n"
"    border: none;\n"
"    padding: 0;\n"
"    background: none;\n"
"}\n"
"\n"
"/* A QToolTip is a QLabel ... */\n"
"QToolTip {\n"
"    border: 2px solid darkkhaki;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"/* Nice to have the background color change when hovered. */\n"
"QRadioButton:hover, QCheckBox:hover {\n"
"    background-color: wheat;\n"
"}\n"
"\n"
"/* Force the dialog\'s buttons to follow the Windows guidelines. */\n"
"QDialogButtonBox {\n"
"    button-layout: 0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 631, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 110, 301, 251))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(120, 20, 171, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_Ad = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Ad.setFont(font)
        self.lineEdit_Ad.setObjectName("lineEdit_Ad")
        self.verticalLayout_2.addWidget(self.lineEdit_Ad)
        self.lineEdit_Soyad = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Soyad.setFont(font)
        self.lineEdit_Soyad.setObjectName("lineEdit_Soyad")
        self.verticalLayout_2.addWidget(self.lineEdit_Soyad)
        self.lineEdit_TCNo = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_TCNo.setFont(font)
        self.lineEdit_TCNo.setMaxLength(11)
        self.lineEdit_TCNo.setObjectName("lineEdit_TCNo")
        self.verticalLayout_2.addWidget(self.lineEdit_TCNo)
        self.widget1 = QtWidgets.QWidget(self.frame)
        self.widget1.setGeometry(QtCore.QRect(30, 20, 71, 121))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.groupBox_Cinsiyet = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Cinsiyet.setGeometry(QtCore.QRect(20, 390, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Cinsiyet.setFont(font)
        self.groupBox_Cinsiyet.setFlat(False)
        self.groupBox_Cinsiyet.setObjectName("groupBox_Cinsiyet")
        self.radioButton_Erkek = QtWidgets.QRadioButton(self.groupBox_Cinsiyet)
        self.radioButton_Erkek.setGeometry(QtCore.QRect(20, 30, 81, 21))
        self.radioButton_Erkek.setObjectName("radioButton_Erkek")
        self.radioButton_Kadin = QtWidgets.QRadioButton(self.groupBox_Cinsiyet)
        self.radioButton_Kadin.setGeometry(QtCore.QRect(160, 30, 81, 21))
        self.radioButton_Kadin.setObjectName("radioButton_Kadin")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(370, 110, 371, 251))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.widget2 = QtWidgets.QWidget(self.frame_2)
        self.widget2.setGeometry(QtCore.QRect(10, 20, 143, 91))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.widget3 = QtWidgets.QWidget(self.frame_2)
        self.widget3.setGeometry(QtCore.QRect(140, 30, 221, 211))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_Dogumyeri = QtWidgets.QComboBox(self.widget3)
        self.comboBox_Dogumyeri.setObjectName("comboBox_Dogumyeri")
        self.verticalLayout_4.addWidget(self.comboBox_Dogumyeri)
        self.listWidget_Dersler = QtWidgets.QListWidget(self.widget3)
        self.listWidget_Dersler.setMouseTracking(False)
        self.listWidget_Dersler.setTabletTracking(True)
        self.listWidget_Dersler.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.listWidget_Dersler.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.listWidget_Dersler.setAcceptDrops(False)
        self.listWidget_Dersler.setToolTip("")
        self.listWidget_Dersler.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget_Dersler.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.listWidget_Dersler.setFrameShape(QtWidgets.QFrame.Box)
        self.listWidget_Dersler.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget_Dersler.setLineWidth(2)
        self.listWidget_Dersler.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget_Dersler.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget_Dersler.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listWidget_Dersler.setAutoScroll(True)
        self.listWidget_Dersler.setAutoScrollMargin(18)
        self.listWidget_Dersler.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidget_Dersler.setTabKeyNavigation(True)
        self.listWidget_Dersler.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget_Dersler.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_Dersler.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget_Dersler.setObjectName("listWidget_Dersler")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Dersler.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Dersler.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Dersler.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Dersler.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Dersler.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Dersler.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Dersler.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Dersler.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Dersler.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Dersler.addItem(item)
        self.verticalLayout_4.addWidget(self.listWidget_Dersler)
        self.groupBox_Egitimturu = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Egitimturu.setGeometry(QtCore.QRect(800, 390, 371, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_Egitimturu.setFont(font)
        self.groupBox_Egitimturu.setObjectName("groupBox_Egitimturu")
        self.radioButton_Haftasonu = QtWidgets.QRadioButton(self.groupBox_Egitimturu)
        self.radioButton_Haftasonu.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.radioButton_Haftasonu.setObjectName("radioButton_Haftasonu")
        self.radioButton_Haftaici = QtWidgets.QRadioButton(self.groupBox_Egitimturu)
        self.radioButton_Haftaici.setGeometry(QtCore.QRect(210, 30, 91, 21))
        self.radioButton_Haftaici.setObjectName("radioButton_Haftaici")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(770, 110, 401, 251))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 131, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.calendarWidget_Dogumtarihi = QtWidgets.QCalendarWidget(self.frame_3)
        self.calendarWidget_Dogumtarihi.setGeometry(QtCore.QRect(20, 40, 341, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calendarWidget_Dogumtarihi.setFont(font)
        self.calendarWidget_Dogumtarihi.setObjectName("calendarWidget_Dogumtarihi")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 490, 1151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName("frame_4")
        self.widget4 = QtWidgets.QWidget(self.frame_4)
        self.widget4.setGeometry(QtCore.QRect(10, 10, 1121, 41))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Kayitekle = QtWidgets.QPushButton(self.widget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_Kayitekle.setFont(font)
        self.pushButton_Kayitekle.setObjectName("pushButton_Kayitekle")
        self.horizontalLayout.addWidget(self.pushButton_Kayitekle)
        self.pushButton_Kayitsil = QtWidgets.QPushButton(self.widget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_Kayitsil.setFont(font)
        self.pushButton_Kayitsil.setObjectName("pushButton_Kayitsil")
        self.horizontalLayout.addWidget(self.pushButton_Kayitsil)
        self.tableWidget_Bilgi = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_Bilgi.setGeometry(QtCore.QRect(20, 580, 1151, 311))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_Bilgi.setFont(font)
        self.tableWidget_Bilgi.setRowCount(1)
        self.tableWidget_Bilgi.setColumnCount(8)
        self.tableWidget_Bilgi.setObjectName("tableWidget_Bilgi")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Bilgi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Bilgi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Bilgi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Bilgi.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Bilgi.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Bilgi.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Bilgi.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Bilgi.setHorizontalHeaderItem(7, item)
        self.tableWidget_Bilgi.horizontalHeader().setDefaultSectionSize(138)
        self.tableWidget_Bilgi.horizontalHeader().setMinimumSectionSize(48)
        self.tableWidget_Bilgi.verticalHeader().setDefaultSectionSize(31)
        self.tableWidget_Bilgi.verticalHeader().setMinimumSectionSize(30)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ögrenci Takip"))
        self.label_2.setText(_translate("MainWindow", "ÖĞRENCİ KAYIT SİSTEMİ"))
        self.label_3.setText(_translate("MainWindow", "Ad :"))
        self.label_4.setText(_translate("MainWindow", "Soyad :"))
        self.label_5.setText(_translate("MainWindow", "TC No :"))
        self.groupBox_Cinsiyet.setTitle(_translate("MainWindow", "Cinsiyet"))
        self.radioButton_Erkek.setText(_translate("MainWindow", "Erkek"))
        self.radioButton_Kadin.setText(_translate("MainWindow", "Kadın"))
        self.label.setText(_translate("MainWindow", "Doğum Yeri :"))
        self.label_6.setText(_translate("MainWindow", "Kayıt Olduğu Dersler :"))
        __sortingEnabled = self.listWidget_Dersler.isSortingEnabled()
        self.listWidget_Dersler.setSortingEnabled(False)
        item = self.listWidget_Dersler.item(0)
        item.setText(_translate("MainWindow", "Matematik"))
        item = self.listWidget_Dersler.item(1)
        item.setText(_translate("MainWindow", "Türkçe"))
        item = self.listWidget_Dersler.item(2)
        item.setText(_translate("MainWindow", "Fizik"))
        item = self.listWidget_Dersler.item(3)
        item.setText(_translate("MainWindow", "Kimya"))
        item = self.listWidget_Dersler.item(4)
        item.setText(_translate("MainWindow", "Biyoloji"))
        item = self.listWidget_Dersler.item(5)
        item.setText(_translate("MainWindow", "İngilizce"))
        item = self.listWidget_Dersler.item(6)
        item.setText(_translate("MainWindow", "Geometri"))
        item = self.listWidget_Dersler.item(7)
        item.setText(_translate("MainWindow", "Coğrafya"))
        item = self.listWidget_Dersler.item(8)
        item.setText(_translate("MainWindow", "Tarih"))
        item = self.listWidget_Dersler.item(9)
        item.setText(_translate("MainWindow", "Vatandaşlık"))
        self.listWidget_Dersler.setSortingEnabled(__sortingEnabled)
        self.groupBox_Egitimturu.setTitle(_translate("MainWindow", "Eğitim Türü"))
        self.radioButton_Haftasonu.setText(_translate("MainWindow", "Hafta Sonu"))
        self.radioButton_Haftaici.setText(_translate("MainWindow", "Hafta İçi"))
        self.label_7.setText(_translate("MainWindow", "Doğum Tarihi :"))
        self.pushButton_Kayitekle.setText(_translate("MainWindow", "Kayıt Ekle"))
        self.pushButton_Kayitsil.setText(_translate("MainWindow", "Kayıt Sil"))
        item = self.tableWidget_Bilgi.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ad"))
        item = self.tableWidget_Bilgi.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_Bilgi.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Soyad"))
        item = self.tableWidget_Bilgi.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TC No"))
        item = self.tableWidget_Bilgi.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cinsiyet"))
        item = self.tableWidget_Bilgi.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Doğum Yeri"))
        item = self.tableWidget_Bilgi.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Doğum Tarihi"))
        item = self.tableWidget_Bilgi.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Eğitim Türü"))
